// Copyright © 2019 Binance
//
// This file is part of Binance. The full Binance copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.3
// source: binance/tsslib/v2/protob/aleo-postsigning.proto

package postsigning

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a BROADCAST message sent to all parties during Round 3 of the Aleo TSS signing protocol.
type PSignRound1Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseShare []byte `protobuf:"bytes,1,opt,name=response_share,json=responseShare,proto3" json:"response_share,omitempty"`
}

func (x *PSignRound1Message) Reset() {
	*x = PSignRound1Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binance_tsslib_v2_protob_aleo_postsigning_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PSignRound1Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSignRound1Message) ProtoMessage() {}

func (x *PSignRound1Message) ProtoReflect() protoreflect.Message {
	mi := &file_binance_tsslib_v2_protob_aleo_postsigning_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSignRound1Message.ProtoReflect.Descriptor instead.
func (*PSignRound1Message) Descriptor() ([]byte, []int) {
	return file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDescGZIP(), []int{0}
}

func (x *PSignRound1Message) GetResponseShare() []byte {
	if x != nil {
		return x.ResponseShare
	}
	return nil
}

type RequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenge []byte `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Response  []byte `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *RequestData) Reset() {
	*x = RequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binance_tsslib_v2_protob_aleo_postsigning_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestData) ProtoMessage() {}

func (x *RequestData) ProtoReflect() protoreflect.Message {
	mi := &file_binance_tsslib_v2_protob_aleo_postsigning_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestData.ProtoReflect.Descriptor instead.
func (*RequestData) Descriptor() ([]byte, []int) {
	return file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDescGZIP(), []int{1}
}

func (x *RequestData) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *RequestData) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_binance_tsslib_v2_protob_aleo_postsigning_proto protoreflect.FileDescriptor

var file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x74, 0x73, 0x73, 0x6c, 0x69, 0x62,
	0x2f, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x2f, 0x61, 0x6c, 0x65, 0x6f, 0x2d,
	0x70, 0x6f, 0x73, 0x74, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x22, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x73, 0x73, 0x6c, 0x69,
	0x62, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x6c, 0x65, 0x6f, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x3b, 0x0a, 0x12, 0x50, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x31, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x22, 0x47, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x61,
	0x6c, 0x65, 0x6f, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDescOnce sync.Once
	file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDescData = file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDesc
)

func file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDescGZIP() []byte {
	file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDescOnce.Do(func() {
		file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDescData = protoimpl.X.CompressGZIP(file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDescData)
	})
	return file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDescData
}

var file_binance_tsslib_v2_protob_aleo_postsigning_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_binance_tsslib_v2_protob_aleo_postsigning_proto_goTypes = []interface{}{
	(*PSignRound1Message)(nil), // 0: binance.tsslib.v2.aleo.postsigning.PSignRound1Message
	(*RequestData)(nil),        // 1: binance.tsslib.v2.aleo.postsigning.RequestData
}
var file_binance_tsslib_v2_protob_aleo_postsigning_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_binance_tsslib_v2_protob_aleo_postsigning_proto_init() }
func file_binance_tsslib_v2_protob_aleo_postsigning_proto_init() {
	if File_binance_tsslib_v2_protob_aleo_postsigning_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_binance_tsslib_v2_protob_aleo_postsigning_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PSignRound1Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binance_tsslib_v2_protob_aleo_postsigning_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_binance_tsslib_v2_protob_aleo_postsigning_proto_goTypes,
		DependencyIndexes: file_binance_tsslib_v2_protob_aleo_postsigning_proto_depIdxs,
		MessageInfos:      file_binance_tsslib_v2_protob_aleo_postsigning_proto_msgTypes,
	}.Build()
	File_binance_tsslib_v2_protob_aleo_postsigning_proto = out.File
	file_binance_tsslib_v2_protob_aleo_postsigning_proto_rawDesc = nil
	file_binance_tsslib_v2_protob_aleo_postsigning_proto_goTypes = nil
	file_binance_tsslib_v2_protob_aleo_postsigning_proto_depIdxs = nil
}
