// Copyright © 2019 Binance
//
// This file is part of Binance. The full Binance copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: protob/bls-encryption.proto

package encryption

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
// Represents an encryption of bls
type EncryptionRound1Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CipherText []byte `protobuf:"bytes,1,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
}

func (x *EncryptionRound1Message) Reset() {
	*x = EncryptionRound1Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protob_bls_encryption_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptionRound1Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionRound1Message) ProtoMessage() {}

func (x *EncryptionRound1Message) ProtoReflect() protoreflect.Message {
	mi := &file_protob_bls_encryption_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionRound1Message.ProtoReflect.Descriptor instead.
func (*EncryptionRound1Message) Descriptor() ([]byte, []int) {
	return file_protob_bls_encryption_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptionRound1Message) GetCipherText() []byte {
	if x != nil {
		return x.CipherText
	}
	return nil
}

//
// Represents an decryption of bls, the cipherText should be used as
type DecryptionRound1Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CipherText []byte `protobuf:"bytes,1,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
}

func (x *DecryptionRound1Message) Reset() {
	*x = DecryptionRound1Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protob_bls_encryption_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptionRound1Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptionRound1Message) ProtoMessage() {}

func (x *DecryptionRound1Message) ProtoReflect() protoreflect.Message {
	mi := &file_protob_bls_encryption_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptionRound1Message.ProtoReflect.Descriptor instead.
func (*DecryptionRound1Message) Descriptor() ([]byte, []int) {
	return file_protob_bls_encryption_proto_rawDescGZIP(), []int{1}
}

func (x *DecryptionRound1Message) GetCipherText() []byte {
	if x != nil {
		return x.CipherText
	}
	return nil
}

//
// Represents a BROADCAST message sent to each party during Round 2 of the BLS TSS keygen protocol.
type DecryptionRound2Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DecryptedShare []byte `protobuf:"bytes,1,opt,name=decryptedShare,proto3" json:"decryptedShare,omitempty"`
}

func (x *DecryptionRound2Message) Reset() {
	*x = DecryptionRound2Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protob_bls_encryption_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptionRound2Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptionRound2Message) ProtoMessage() {}

func (x *DecryptionRound2Message) ProtoReflect() protoreflect.Message {
	mi := &file_protob_bls_encryption_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptionRound2Message.ProtoReflect.Descriptor instead.
func (*DecryptionRound2Message) Descriptor() ([]byte, []int) {
	return file_protob_bls_encryption_proto_rawDescGZIP(), []int{2}
}

func (x *DecryptionRound2Message) GetDecryptedShare() []byte {
	if x != nil {
		return x.DecryptedShare
	}
	return nil
}

var File_protob_bls_encryption_proto protoreflect.FileDescriptor

var file_protob_bls_encryption_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x2f, 0x62, 0x6c, 0x73, 0x2d, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x62,
	0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x73, 0x73, 0x6c, 0x69, 0x62, 0x2e, 0x42, 0x4c,
	0x53, 0x2e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x17,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x69, 0x70,
	0x68, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x22, 0x39, 0x0a, 0x17, 0x44, 0x65, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x65,
	0x78, 0x74, 0x22, 0x41, 0x0a, 0x17, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x64, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x64, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x42, 0x4c, 0x53, 0x2f, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protob_bls_encryption_proto_rawDescOnce sync.Once
	file_protob_bls_encryption_proto_rawDescData = file_protob_bls_encryption_proto_rawDesc
)

func file_protob_bls_encryption_proto_rawDescGZIP() []byte {
	file_protob_bls_encryption_proto_rawDescOnce.Do(func() {
		file_protob_bls_encryption_proto_rawDescData = protoimpl.X.CompressGZIP(file_protob_bls_encryption_proto_rawDescData)
	})
	return file_protob_bls_encryption_proto_rawDescData
}

var file_protob_bls_encryption_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protob_bls_encryption_proto_goTypes = []interface{}{
	(*EncryptionRound1Message)(nil), // 0: binance.tsslib.BLS.encryption.EncryptionRound1Message
	(*DecryptionRound1Message)(nil), // 1: binance.tsslib.BLS.encryption.DecryptionRound1Message
	(*DecryptionRound2Message)(nil), // 2: binance.tsslib.BLS.encryption.DecryptionRound2Message
}
var file_protob_bls_encryption_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protob_bls_encryption_proto_init() }
func file_protob_bls_encryption_proto_init() {
	if File_protob_bls_encryption_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protob_bls_encryption_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptionRound1Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protob_bls_encryption_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptionRound1Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protob_bls_encryption_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptionRound2Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protob_bls_encryption_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protob_bls_encryption_proto_goTypes,
		DependencyIndexes: file_protob_bls_encryption_proto_depIdxs,
		MessageInfos:      file_protob_bls_encryption_proto_msgTypes,
	}.Build()
	File_protob_bls_encryption_proto = out.File
	file_protob_bls_encryption_proto_rawDesc = nil
	file_protob_bls_encryption_proto_goTypes = nil
	file_protob_bls_encryption_proto_depIdxs = nil
}
